import TermsConditionCard from "@/components/terms-condition/TermsConditionCard";
import React from "react";

export const metadata = {
  title: "Terms & Conditions | Bubble Dive",
  description: "Generated by create next app",
};

const TermsAndCondition = () => {
  return (
    <>
      <TermsConditionCard />
    </>
  );
};

export default TermsAndCondition;
